base_images:
  base:
    name: "4.17"
    namespace: ocp
    tag: base
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.22
images:
- dockerfile_path: Dockerfile.download
  from: base
  to: oadp-cli-binaries
promotion:
  to:
  - name: oadp-cli-binaries
    namespace: konveyor
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
zz_generated_metadata:
  branch: oadp-dev
  org: migtools
  repo: oadp-cli